# SERVER
server:
  port: 28082
local:
  server:
    port: 28082

# CLOUD
spring:
  cloud:
    config:
      overrideNone: true
      overrideSystemProperties: false
  jpa:
    show-sql: true
  hibernate:
    ddl-auto: validate
  properties:
    hibernate:
      format_sql: true
      temp:
        use_jdbc_metadata_defaults: false
  database-platform: org.hibernate.dialect.PostgreSQL94Dialect

# DATASOURCE
#spring.datasource.url=jdbc:postgresql://5.196.95.68:28183/lpdm-order
#spring.datasource.username=lpdm
#spring.datasource.password=lpdm

# HIBERNATE







# APPLICATION
microservice.domain=localhost
microservice.auth.name=microservice-authentication
microservice.auth.port=28081
microservice.product.name=ms-product
microservice.product.port=28085

#EUREKA
eureka:
  client:
    serviceUrl:
      defaultZone:
        https://eureka.lpdm.kybox.fr/eureka
