# SERVER
server:
  port: 28082
local:
  server:
    port: 28082

# CLOUD
spring:
  cloud:
    config:
      overrideNone: true
      overrideSystemProperties: false
  jpa:
  hibernate:
    ddl-auto: validate
  properties:
    hibernate:
      format_sql: true
      temp:
        use_jdbc_metadata_defaults: false
  database-platform: org.hibernate.dialect.PostgreSQL94Dialect

# JWT
lpdm:
  jwt:
    header: Authorization
    prefix: Bearer
    expiration: 86400
    secret: lpdm::jwtoken+s=







# APPLICATION
#microservice.domain=localhost
#microservice.auth.name=microservice-authentication
#microservice.auth.port=28081
#microservice.product.name=ms-product
#microservice.product.port=28085

#EUREKA
eureka:
  client:
    serviceUrl:
      defaultZone: https://eureka.lpdm.kybox.fr/eureka
