# SERVER
server:
  port: 28083

# SPRING
spring:

  # CLOUD
  cloud:
    config:
      overrideNone: true
      overrideSystemProperties: false

  # DATASOURCE
  datasource:
    url: ENC(f9wdmIU1m+XCMPHtbGtPuMWwM086f3V6lkoJRB63Pg0iD5ZxYE0QU3KsQGVAKtexG+DPvAMgh59foMz8Rqg9dg==)
    username: ENC(aLRQDMWGqspFONkQl63FfA==)
    password: ENC(pNcu3LX0qFhoE4t3omKKcA==)

  # HIBERNATE
  jpa:
    hibernate:
      ddl-auto: validate
    database-platform: org.hibernate.dialect.PostgreSQL94Dialect
    properties:
      hibernate:
        format_sql: true
        temp:
            use_jdbc_metadata_defaults: false
# EUREKA
eureka:
  client:
    service-url:
      defaultZone: https://eureka.lpdm.kybox.fr/eureka
          
# PAYPAL SANDBOX
paypal:
  clientid: ENC(skXmwY/crcUH/Vf1iMNQrYYxsn7TMN820DK01507eFPjFBn6Z5KiuQLfufCcGYt+lPQAB4c2/3X7ezLLxoybQBn2PNFwiTamCR0g6ESb9zrYDwj+4MfxKIiCINn53uK6)
  secret: ENC(WhtIko+bQgE/8iPFc4nYPwTFL50F/ecRm5Y4pAcVASzyTx6NUdF8cIueNT9sItL+HgeS2QbKTwLr2tcce4yeEuuGTSPAfSUD8T/NGpZf0uU3QK3Wpr0tSVquLVmEJ0LJ)