server:
  port: 28085
spring:
  cloud:
    config:
      overrideNone: true
      overrideSystemProperties: false
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        format_sql: true
        temp:
          use_jdbc_metadata_defaults: false
    database-platform: org.hibernate.dialect.PostgreSQL94Dialect
  datasource:
    url: jdbc:postgresql://91.121.110.162:28186/db_stock
    username: usr_stock
    password: stock
eureka:
  client:
    serviceUrl: {"defaultZone":"https://eureka.lpdm.kybox.fr/eureka"}