# SERVER
server:
  port: 28089

# SPRING
spring:

  # CLOUD
  cloud:
    config:
      overrideNone: true
      overrideSystemProperties: false

  # DATASOURCE
  datasource:
    url: jdbc:postgresql://91.121.110.162:28189/lpdm-storage
    username: lpdm
    password: lpdm

  # HIBERNATE
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: validate
    database-platform: org.hibernate.dialect.PostgreSQL94Dialect
    properties:
      hibernate:
        format_sql: true
        temp:
          use_jdbc_metadata_defaults: false