# SERVER
server:
  port: 28084

# SPRING
spring:

  # CLOUD
  cloud:
    config:
      overrideNone: true
      overrideSystemProperties: false

  # DATASOURCE
  datasource:
    url: ENC(AeeJK44fcv7KOL6hMCucljAAFRYcG7JSud7MAwqVKZ+7YHCQZPmps6W5SgiA7bH0rlCZ1R2+l8N2ty+33ub6pA==)
    username: ENC(ISTBcwXTVCtOYIO500zqcA==)
    password: ENC(XPAAYLcMpBFt5Hm7lSUfbA==)

  # HIBERNATE
  jpa:
    hibernate:
      ddl-auto: validate
    database-platform: org.hibernate.dialect.PostgreSQL94Dialect
    properties:
      hibernate:
        format_sql: true
        temp:
            use_jdbc_metadata_defaults: false
# EUREKA
eureka:
  client:
    service-url:
      defaultZone: https://eureka.lpdm.kybox.fr/eureka