# SERVER
server:
  port: 28084

# SPRING
spring:

  # CLOUD
  cloud:
    config:
      overrideNone: true
      overrideSystemProperties: false

  # DATASOURCE
  datasource:
    url: ENC(er5WytigFa8IK7egoJ6TB8+0pq0vva8pRYr/VoN+Hso2RvPK3JzDJ3z58DLcds4WIbBpYN9/9QpZZhXrtR6Bow==)
    username: ENC(Mhn6DjftFQDGj6uRC8ihCA==)
    password: ENC(a5YM8tTfLZ08v+BqjPGN7A==)

  # HIBERNATE
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: validate
    database-platform: org.hibernate.dialect.PostgreSQL94Dialect
    properties:
      hibernate:
        format_sql: true
        temp.use_jdbc_metadata_defaults: false