# SERVER
server:
  port: 28090
local:
  server:
    port: 28090

#ZUUL ROUTES
zuul:
  routes:
    ms-userentity:
      url: http://localhost:28080
    microservice-authentication:
      url: https://auth.lpdm.kybox.fr
      sensitiveHeaders: Cookie,Set-Cookie
    microservice-users:
      url: https://lpdm.kybox.fr
    ms-order:
      url: https://order.lpdm.kybox.fr
    ms-store:
      url: https://store.lpdm.kybox.fr
    ms-product:
      url: https://product.lpdm.kybox.fr
    ms-stock:
      url: https://stock.lpdm.kybox.fr
    ms-location:
      url: https://location.lpdm.kybox.fr
    ms-storage:
      url: https://storage.lpdm.kybox.fr

#EUREKA
eureka:
  client:
    serviceUrl:
      defaultZone:
        https://eureka.lpdm.kybox.fr/eureka

#Spring Security
spring:
  security:
    user:
      name: utilisateur
      password: mdp
